### PR TITLE
Update odroidxu4 legacy kernel to 4.14.173

### PR DESCRIPTION
**Pull request by belegdol**
I have built an updated legacy odroidxu4 kernel following HK's update with the following command:
```
./compile.sh KERNEL_ONLY=yes KERNEL_CONFIGURE=no KERNEL_KEEP_CONFIG=no BOARD=odroidxu4 USE_CCACHE=no BRANCH=legacy
```
Smoke test consisting of reboot and poweroff followed by disconnecting and reconnecting power has passed.
The source package can be downloaded from dropbox as usual:
https://www.dropbox.com/s/jfolk74tqc3g00z/linux-source-legacy-odroidxu4_20.05.0-trunk_all.deb?dl=0

### CODE REVIEW

**Comment by igorpecovnik** [comment]
Since we changed versioning, its better to provide upgrades with a version that is (at least) one minor bigger than current 20.02.1 ... manually change VERSION to biggest https://docs.armbian.com/Release_Changelog/ and recompile. I know its more work for you, but sticking to proper versioning is also an added value. Sorry for troubles.

**Comment by belegdol** [comment]
No worries, I can change the version. I am not sure to what though: 20.05.0-trunk is 3 minor versions ahead of both 20.02.1 and 20.02.3.
I can checkout v20.02 branch of build, bump version to 20.02.4 and rebuild. Would this work?

ETA: in general, should point release updates to the kernel be built from master, from release branch, or from both?

**Comment by igorpecovnik** [comment]
Stay on master, just manually change VERSION to 20.02.3, rebuild and upload.

> in general, should point release updates to the kernel be built from master, from release branch, or from both?

For kernel it should be pretty much irrelevant, but better do the suggested way.

**Comment by belegdol** [comment]
Rebuild done, here is the new dropbox link:
https://www.dropbox.com/s/s2ywob86vtkl3p1/linux-source-legacy-odroidxu4_20.02.3_all.deb?dl=0
I have only tested soft reboot this time.

**Pull request merged**
