### PR TITLE
Update odroidxu4 current kernel to 5.4.91

### PR DESCRIPTION
**Pull request by belegdol**
I have built an updated current odroidxu4 kernel following HK's update with the following command:
```
./compile.sh BOARD=odroidxu4 BRANCH=current KERNEL_ONLY=yes KERNEL_CONFIGURE=no USE_CCACHE=no KEEP_KERNEL_CONFIG=no
```
Kernel is built from https://github.com/armbian/build/pull/2569 with version manually changed to 20.11.9.
The issue of SATA drive disappearing after soft reset seems to be finally gone.
I will post the dropbox link later, upload is extremely slow somehow.

### CODE REVIEW

**Comment by igorpecovnik** [comment]
we have alternative, should be faster. Send ssh key to igor at armbian.com

**Comment by belegdol** [comment]
It appears to have nothing to do with dropbox, I am getting approx. 10 % of the bandwith at the modem. Hopefully it will work better tomorrow.

**Comment by belegdol** [comment]
Source package link:
https://www.dropbox.com/s/0zjm7y0el1ce4ko/linux-source-current-odroidxu4_20.11.9_all.deb?dl=0

**Comment by belegdol** [comment]
@igorpecovnik, I can see the update has now been included in the official repositories even though the PR is still not merged. Has the way of submitting updated packages changed?

**Comment by igorpecovnik** [comment]
This method still works, but its troublesome due to size limits. It add additional tasks ... I had to rebuild all other images due to other bugs so updating xu4 kernel was made more or less automatic in that process. 

Otherwise we have a daemon that monitors upstream changes, patch and config changes ... and it automatically rebuilds kernels and pushes them to repository. This is currently enabled on beta repository and will once be moved to stable. This means at least the part of uploading packages, won't be needed anymore. Also for updating packages, we enabled SFTP access to drop directory. Its similar to this system, manual intervention is still needed, but there are no file size limits.

**Pull request closed without merging**
